// ═══════════════════════════════════════════════════════════════════════
//  DADOS DO RADAR DE CONCURSOS · Aula Nota 10
//  Última verificação: 11/09/2026
//
//  ESTE É O ÚNICO ARQUIVO QUE VOCÊ PRECISA EDITAR PARA ATUALIZAR O SITE.
//  Não mexa no index.html.
//
//  ── TIPOS DE DATA ──
//  { tipo: "exata",         valor: "2026-11-23" }
//  { tipo: "periodo",       valor: "2026-09-03", fim: "2026-11-06" }
//  { tipo: "nao_divulgada", nota: "Sai após a prova escrita" }
//
//  ── TIPOS DE ETAPA (campo "tipo") ──
//  objetiva · discursiva · didatica · titulos · memorial · resultado · outra
//
//  ── REGRA DE OURO ──
//  Nunca preencha data que não esteja publicada em fonte oficial.
//  Sem data confirmada, use { tipo: "nao_divulgada" } e explique na nota.
// ═══════════════════════════════════════════════════════════════════════

window.RADAR_ATUALIZADO = "11/09/2026";

window.CONCURSOS = [

  // ══════════ UFRN · Edital 058/2026 (MS · escrita em 13/09 · didática 14/09 a 02/10) ══════════
  {
    id: "ufrn-058-2026", logo: "ufrn.png",
    uf: "RN", sigla: "UFRN",
    instituicao: "Universidade Federal do Rio Grande do Norte",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 058/2026-PROGESP",
    areas: "26 vagas em saúde (Nutrição, Medicina, Odontologia, Fonoaudiologia, Enfermagem), exatas e tecnologia (Arquitetura, Física, Matemática, Geologia, Computação, Engenharia Econômica), humanas e educação (Educação, História, Ciência da Informação, Serviço Social, Artes, Comunicação, Letras, Políticas Públicas) e Música",
    vagas: "26 vagas (5 PcD, 6 pretos e pardos, 1 indígena, 1 quilombola)",
    campi: "Natal, CERES, FACISA e FELCS",
    titulacao: "Doutorado na área. Mestrado em parte das vagas, conforme o Anexo",
    remuneracao: "R$ 14.945,96 (DE com doutorado) · R$ 9.532,33 (40h doutorado) · R$ 5.633,78 (20h doutorado)",
    regime: "Dedicação exclusiva, 40h ou 20h conforme a vaga",
    banca: "Coordenadoria de Concursos da PROGESP, com comissões por área",
    link_oficial: "https://sigrh.ufrn.br/publico/concursos/316?previousLink=em-andamento",
    inscricao: { inicio: "2026-05-18", fim: "2026-06-16", situacao: "encerrada", taxa: "R$ 220,00 (DE), R$ 180,00 (40h), R$ 150,00 (20h)" },
    detalhamento: "completo",
    etapas: [
      { nome: "Entrega eletrônica do Memorial e Projeto de Atuação Profissional (MPAP)", tipo: "outra", carater: "",
        data: { tipo: "periodo", valor: "2026-07-06", fim: "2026-07-17", nota: "Já realizada" }, detalhe: {} },
      { nome: "Divulgação das comissões examinadoras e dos calendários por área", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-08-10", nota: "Já realizada" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-13", nota: "Às 8h, em Natal/RN, para todas as áreas" },
        detalhe: { nota_minima: "7,0",
                   local: "Setor III da UFRN, Natal/RN (locais retificados em 09/09)",
                   formato: "Cláusula de barreira: classifica até 5 candidatos por lista para as etapas seguintes" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-09-14", fim: "2026-10-02", nota: "A data exata da sua área está no calendário da comissão examinadora, divulgado em 10/08" },
        detalhe: { duracao: "Aula de 50 a 60 minutos. A arguição encerra aos 60 minutos",
                   sorteio: "Sim. O ponto é sorteado no dia da prova escrita, 13/09, por envelope, random.org ou planilha, com comprovante assinado por dois fiscais",
                   nota_minima: "7,00",
                   arguicao: "Sim, obrigatória para todos os membros da banca. Até 3 minutos de pergunta por membro e até 5 minutos de resposta",
                   modalidade: "Presencial obrigatória para o candidato. A comissão examinadora participa prioritariamente por videoconferência. Sessão pública, no máximo 3 candidatos por turno, com gravação em áudio e vídeo",
                   plano_de_aula: "Entregue em PDF na chegada. O candidato deve comparecer com no mínimo 30 minutos de antecedência",
                   criterios: "Plano de aula (0 a 2), aspectos didático-metodológicos (0 a 5), recursos didáticos (0 a 1) e arguição (0 a 2)" } },
      { nome: "Defesa do Memorial e Projeto de Atuação Profissional", tipo: "memorial", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-09-14", fim: "2026-10-02" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-09-14", fim: "2026-10-02" }, detalhe: {} },
      { nome: "Avaliação biopsicossocial (candidatos PcD)", tipo: "outra", carater: "",
        data: { tipo: "periodo", valor: "2026-10-05", fim: "2026-10-09" }, detalhe: {} },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "O ponto da aula sai no mesmo dia da prova escrita, 13/09, e a janela da didática é apertada: aula, defesa de memorial e títulos entre 14/09 e 02/10. São três eliminatórias com mínimo 7,0 cada. O plano de aula vale 2 dos 10 pontos da didática e é entregue 30 minutos antes, em PDF. É ponto que se ganha em casa."
  },

  // ══════════ UFRGS · Edital 09/2026 (MS · inscrição encerrada em 09/09) ══════════
  {
    id: "ufrgs-09-2026", logo: "ufrgs.png",
    uf: "RS", sigla: "UFRGS",
    instituicao: "Universidade Federal do Rio Grande do Sul",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 09/2026",
    areas: "16 áreas em vários departamentos, com Antropologia, Educação, Língua Alemã e Odontologia com 2 vagas cada",
    vagas: "20 vagas (10 ampla concorrência, 5 pretos, 1 indígena, 4 PcD)",
    campi: "Porto Alegre e demais unidades da UFRGS",
    titulacao: "Doutorado obrigatório em todas as vagas. Algumas exigem graduação específica (Arquitetura, Medicina com residência em Nefrologia)",
    remuneracao: "R$ 13.753,96 em dedicação exclusiva. R$ 8.340,33 na vaga de Nefrologia (40h)",
    regime: "Dedicação exclusiva, exceto a vaga de Nefrologia (40h)",
    banca: "PROGESP/UFRGS",
    link_oficial: "https://www.ufrgs.br/progesp/pagina-inicial/concursos-e-processos-seletivos/1939-2/concursos-2/",
    inscricao: { inicio: "2026-08-26", fim: "2026-09-09", situacao: "encerrada", taxa: "R$ 340,00 (DE) ou R$ 209,00 (40h). Pagamento até 11/09" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma publicado pela comissão de cada departamento, após a homologação das inscrições" },
        detalhe: { nota_minima: "7,0" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma por departamento, normalmente algumas semanas após o fim do prazo de inscrição" },
        detalhe: { nota_minima: "7,0",
                   modalidade: "Presencial, na unidade da vaga" } },
      { nome: "Defesa de Produção Intelectual", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Inscrição encerrada em 09/09. A nota mínima 7,0 vale para cada etapa, então não dá para compensar didática fraca com prova escrita boa."
  },

  // ══════════ UFSCar · Edital Único 004/2026 (MS · 89 vagas · inscrição fecha em 11/09) ══════════
  {
    id: "ufscar-004-2026", logo: "ufscar.png",
    uf: "SP", sigla: "UFSCAR", sigla_selo: "UFSCar",
    instituicao: "Universidade Federal de São Carlos",
    nivel: "Magistério Superior",
    numero_edital: "Edital Único nº 004/2026",
    areas: "89 subeditais cobrindo engenharias, exatas, saúde, humanas e linguagens",
    vagas: "89 vagas (57 ampla concorrência, 22 pretos e pardos, 3 indígenas, 2 quilombolas, 5 PcD)",
    campi: "São Carlos, Araras, Sorocaba, Lagoa do Sino e São José do Rio Preto",
    titulacao: "Doutorado na maioria das vagas. Alguns subeditais aceitam mestrado ou especialização",
    remuneracao: "R$ 13.753,96 (doutor, DE) · R$ 9.595,78 (mestre, DE) · R$ 3.518,45 (especialista, 20h)",
    regime: "Dedicação exclusiva na maioria das vagas",
    banca: "ProGPe/UFSCar",
    link_oficial: "https://www.progpe.ufscar.br/concursos-e-selecoes",
    inscricao: { inicio: "2026-08-21", fim: "2026-09-11", situacao: "aberta", taxa: "R$ 275,00 por vaga" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-10-18", nota: "Às 13h30, duração de 4 horas, presencial" },
        detalhe: { duracao: "4 horas", modalidade: "Presencial" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-11-24", fim: "2026-12-15" },
        detalhe: { modalidade: "Presencial",
                   sorteio: "A data e o horário de cada candidato são definidos por sorteio. A regra do sorteio do ponto e a duração da aula constam do subedital da área",
                   formato: "Em português, exceto os códigos 004/26.27 (espanhol) e 004/26.54 (Libras)" } },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2027-01-27" }, detalhe: {} }
    ],
    observacao: "Janela de didática longa, quase um mês entre 24/11 e 15/12. Dá tempo de preparar bem depois da escrita de outubro. Aqui a didática é classificatória, ou seja, decide a colocação e não a eliminação. Confira a duração da aula no subedital da sua área."
  },

  // ══════════ UNESPAR · Edital 023/2026-CPPS (MS · sorteio do ponto 4 semanas antes da aula) ══════════
  {
    id: "unespar-023-2026", logo: "unespar.png",
    uf: "PR", sigla: "UNESPAR",
    instituicao: "Universidade Estadual do Paraná",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 023/2026-CPPS, retificado pelos Editais nº 025/2026-CPPS e nº 029/2026-CPPS",
    areas: "Medicina e saúde, Ciências Contábeis, Agronomia, Pedagogia e Fundamentos da Educação, Letras e Inglês, Ciências Biológicas, Enfermagem, Música e Canto, Cinema, Artes Visuais e Musicoterapia",
    vagas: "23 vagas (confira o Anexo I para a distribuição por campus)",
    campi: "Apucarana, Campo Mourão, Curitiba I, Curitiba II, Paranaguá e União da Vitória",
    titulacao: "Varia por vaga. Em geral graduação na área mais mestrado ou doutorado. As retificações 025/2026 e 029/2026 flexibilizaram requisitos em algumas vagas. O 029/2026 passou a aceitar doutorado em Fisiologia Vegetal na vaga ID 1414 (Campo Mourão)",
    remuneracao: "TIDE: R$ 16.565,27 bruto (vencimento R$ 8.080,62 + adicional de titulação R$ 8.484,65). T-34: R$ 9.084,12 bruto",
    regime: "Estatutário (RPPS), em TIDE ou T-34 conforme a vaga",
    banca: "CPPS/PROGESP UNESPAR",
    link_oficial: "https://progesp.unespar.edu.br/menu-principal/concursos-publicos/concurso-publico/edital-n-023-2026-cpps",
    inscricao: { inicio: "2026-09-03", fim: "2026-09-16", situacao: "aberta", taxa: "R$ 250,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Sorteio dos pontos da prova escrita e da prova didática", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-18", nota: "Às 8h30. O ponto da aula sai neste dia" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória · peso 3",
        data: { tipo: "exata", valor: "2026-10-18" },
        detalhe: { duracao: "Até 4 horas", nota_minima: "7,0",
                   formato: "Inclui questão obrigatória sobre o ECA" } },
      { nome: "Resultado da prova escrita", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-11-03" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória · peso 4",
        data: { tipo: "periodo", valor: "2026-11-16", fim: "2026-11-26", nota: "Ensalamento divulgado em 10/11" },
        detalhe: { duracao: "Aula de 30 a 40 minutos, mais 15 minutos de arguição. Em algumas vagas há mais 15 minutos de etapa extra (portfólio, entrevista ou prática)",
                   sorteio: "Sim, mas o ponto é sorteado em 18/10, quase quatro semanas antes da aula",
                   nota_minima: "7,00",
                   arguicao: "Sim, 15 minutos",
                   modalidade: "Presencial, aberta ao público. Gravação proibida",
                   plano_de_aula: "Três cópias impressas entregues no início da prova, sob pena de eliminação",
                   peso: "Peso 4, o maior do certame" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória · peso 3",
        data: { tipo: "periodo", valor: "2026-11-16", fim: "2026-11-26" },
        detalhe: { criterios: "Análise do Currículo Lattes, escala de 0 a 10" } },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2026-12-08", nota: "Preliminar a partir de 01/12. Homologação a partir de 10/12" }, detalhe: {} }
    ],
    observacao: "O ponto da aula sai em 18/10 e a aula só acontece a partir de 16/11. São quase quatro semanas com o tema na mão, então aqui ninguém perde por falta de tempo, perde por preparação genérica. Com peso 4, a banca espera aula ensaiada e cronometrada. Esquecer as três cópias impressas do plano de aula elimina."
  },

  // ══════════ UERJ · seleções por departamento (MS · 17 seleções abertas) ══════════
  {
    id: "uerj-2026", logo: "uerj.png",
    uf: "RJ", sigla: "UERJ",
    instituicao: "Universidade do Estado do Rio de Janeiro",
    nivel: "Magistério Superior",
    numero_edital: "17 seleções abertas (2026/213, 224, 225, 226, 229, 230, 231, 232, 233, 234, 236, 238, 239, 243, 245, 250 e 251)",
    areas: "Ciência da Computação, Metodologia e Técnicas de Computação, Engenharia Econômica, Física Geral, Geografia e Ensino de Geografia, Ciências Ambientais, Engenharia Ambiental, Clínica Médica, Gastroenterologia, Endocrinologia, Fisiatria, Hematologia, Ginecologia e Obstetrícia, Nefrologia e Sistemas Elétricos de Potência (2 seleções)",
    vagas: "1 a 2 vagas por seleção, em 17 seleções independentes",
    campi: "Maracanã, Resende, Cabo Frio e unidades de saúde em Vila Isabel (HUPE, Policlínica Piquet Carneiro, CEPEM)",
    titulacao: "Doutorado na área (Adjunto), com exigência de graduação específica em várias seleções. Mestrado na 2026/229 (Professor Assistente, Clínica Médica)",
    remuneracao: "Vencimento base de R$ 6.950,85 (Adjunto) ou R$ 5.236,22 (Assistente) nas seleções com errata, e R$ 6.581,01 nas demais, com adicional de 65% em dedicação exclusiva",
    regime: "Estatutário estadual, 40 horas",
    banca: "Comissões examinadoras dos departamentos, gestão da SGP/DESENP",
    link_oficial: "https://prossim.uerj.br/",
    inscricao: { inicio: "2026-08-17", fim: "2027-01-31", situacao: "aberta", taxa: "R$ 261,81 a R$ 347,54, conforme a seleção. Cada seleção tem prazo próprio: a 2026/224 vai até 31/01/2027" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-26", fim: "2027-03-15", nota: "Cada seleção tem data própria. Geografia 26/10; Clínica Médica (229 e 230), Fisiatria, Hematologia e Gastroenterologia 03/11; Endocrinologia 04/11; Física Geral, Ginecologia e Obstetrícia e Nefrologia 09/11; Engenharia Ambiental e Ciências Ambientais 23/11; Sistemas Elétricos 2026/250 30/11; Engenharia Econômica 01/12; Sistemas Elétricos 2026/251 07/12; Metodologia e Técnicas de Computação 08/12; Ciência da Computação 15/03/2027" },
        detalhe: { duracao: "4 horas", formato: "Ponto sorteado poucos minutos antes do início da prova" } },
      { nome: "Prova de Aula", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-30", fim: "2027-03-18", nota: "Cada seleção tem data própria. Geografia 30/10; Gastroenterologia 04/11; Clínica Médica (229 e 230) e Fisiatria 05/11; Hematologia e Endocrinologia 06/11; Ginecologia e Obstetrícia e Nefrologia 11/11; Física Geral 12/11; Engenharia Ambiental e Ciências Ambientais 26/11; Sistemas Elétricos 2026/250 02/12; Engenharia Econômica 03/12; Sistemas Elétricos 2026/251 09/12; Metodologia e Técnicas de Computação 10/12; Ciência da Computação 18/03/2027" },
        detalhe: { duracao: "Aula de 50 a 60 minutos",
                   sorteio: "Sim. Ponto sorteado com 24 horas de antecedência, a partir de uma lista de no mínimo 10 pontos do programa divulgada pela banca",
                   nota_minima: "7,0 na maioria das seleções. Confira no edital da sua seleção",
                   modalidade: "Presencial, em sessão pública e em português. Os candidatos não assistem à aula uns dos outros",
                   criterios: "Três examinadores avaliam capacidade de comunicação, atualização, profundidade de conhecimento e precisão" } },
      { nome: "Entrega de títulos e trabalhos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-30", fim: "2027-03-19", nota: "Em geral no dia da prova de aula ou no dia seguinte. Nas seleções 225 e 226, em 27/11. Na 2026/250, após a prova prática de 04/12" }, detalhe: {} },
      { nome: "Prova Prática (em parte das seleções)", tipo: "outra", carater: "",
        data: { tipo: "periodo", valor: "2026-12-04", fim: "2027-03-19", nota: "2026/250 em 04/12/2026 e 2026/224 em 19/03/2027" }, detalhe: {} },
      { nome: "Defesa de projeto (em parte das seleções)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Confirmada na seleção de Física Geral, em 13/11" }, detalhe: {} },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "nao_divulgada", nota: "Por seleção, em geral até 7 dias úteis após a última etapa. Nas seleções 2026/239 e 2026/245, até 18/12/2026" }, detalhe: {} }
    ],
    observacao: "Na UERJ o jogo é a virada de 24 horas: o ponto sai um dia antes, quase sempre no dia seguinte à prova escrita, e você entra em sala na manhã seguinte. Não dá para montar a aula na hora, tem que chegar com as 10 possibilidades já pré-montadas. E a aula é longa, 50 a 60 minutos, exige aula de verdade e não resumo apressado. Cada departamento abre a sua seleção, com cronograma próprio: confira o seu em prossim.uerj.br."
  },

  // ══════════ UNILA · Edital 204/2026 (MS · inscrição fecha em 13/09 · didática 20 e 21/10) ══════════
  {
    id: "unila-204-2026", logo: "unila.png",
    uf: "PR", sigla: "UNILA",
    instituicao: "Universidade Federal da Integração Latino-Americana",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 204/2026/DICS/DAP/PROGEPE, com Edital de conteúdo específico nº 205/2026",
    areas: "Humanidades e Ciências Sociais, subárea Comunicação, Mediação Cultural, Letras ou Artes",
    vagas: "1 vaga, ampla concorrência",
    campi: "Foz do Iguaçu/PR",
    titulacao: "Graduação em Comunicação, Mediação Cultural, Produção Cultural ou Gestão Cultural, mais doutorado em Comunicação, Artes, Letras, Produção Cultural, Mediação Cultural ou Gestão Cultural",
    remuneracao: "R$ 13.288,85 (vencimento R$ 6.180,86 + RT R$ 7.107,99)",
    regime: "40 horas com dedicação exclusiva",
    banca: "PROGEPE/UNILA",
    link_oficial: "https://documentos.unila.edu.br/concursos/204-2026-1",
    inscricao: { inicio: "2026-07-30", fim: "2026-09-13", situacao: "aberta", taxa: "R$ 215,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Homologação das inscrições", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-21", nota: "A partir desta data" }, detalhe: {} },
      { nome: "Divulgação da banca examinadora", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-30" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-10-19", nota: "Das 9h às 13h. Resultado até 12h de 20/10" },
        detalhe: { nota_minima: "7,00" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-20", fim: "2026-10-21", nota: "20/10 das 14h às 18h e 21/10 das 8h às 12h. Cronograma prévio do Edital 205/2026, sujeito a alteração" },
        detalhe: { duracao: "45 minutos",
                   sorteio: "Sim. Ponto sorteado após a entrega da prova escrita, de uma lista de 10 pontos publicada no Edital 205/2026",
                   modalidade: "Presencial, em sessão fechada" } },
      { nome: "Defesa da Proposta de Atuação Acadêmica", tipo: "memorial", carater: "Classificatória",
        data: { tipo: "exata", valor: "2026-10-22", nota: "Das 8h às 18h" }, detalhe: {} },
      { nome: "Análise de Títulos e Currículo", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-20", fim: "2026-10-23", nota: "Após a conclusão da prova didática" }, detalhe: {} },
      { nome: "Resultado provisório", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2026-10-23", nota: "Homologação do resultado final a partir de 29/10" }, detalhe: {} }
    ],
    observacao: "Tudo acontece em quatro dias: escrita em 19/10 e aula já em 20 ou 21/10, com o ponto sorteado depois que você entrega a escrita. Os 10 pontos estão publicados no Edital 205/2026, então a aula de 45 minutos precisa estar pronta para qualquer um deles antes de você viajar. Confira se a sua formação bate exatamente com a combinação de graduação e doutorado exigida."
  },

  // ══════════ UFSM · Edital 221/2026 (MS · inscrição fecha em 23/09) ══════════
  {
    id: "ufsm-221-2026", logo: "ufsm.png",
    uf: "RS", sigla: "UFSM",
    instituicao: "Universidade Federal de Santa Maria",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 221/2026",
    areas: "Vagas em múltiplos departamentos. Consulte o quadro do edital",
    vagas: "9 vagas",
    campi: "Santa Maria/RS e demais unidades",
    titulacao: "Doutorado na maioria das vagas. Uma parte exige especialização, em 40h",
    remuneracao: "Conforme titulação e regime",
    regime: "Dedicação exclusiva e 40 horas, conforme a vaga",
    banca: "PROGEP/UFSM",
    link_oficial: "https://www.ufsm.br/pro-reitorias/progep/editais/221-2026",
    inscricao: { inicio: "2026-08-25", fim: "2026-09-23", situacao: "aberta", taxa: "R$ 412,60 (doutorado DE), R$ 250,00 (doutorado 40h), R$ 154,00 (especialização 40h). GRU até 24/09" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma detalhado por área, publicado após o encerramento das inscrições" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "O edital informa período provável de início das provas entre 08/11/2026 e 21/02/2027. O cronograma por área sai após o fim das inscrições" },
        detalhe: {} },
      { nome: "Prova Prática (quando houver)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Defesa de Produção Intelectual", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "A UFSM abre uma janela larga de provas, então a didática pode cair de novembro a fevereiro. Preparação longa, com a defesa de produção intelectual junto, que muita gente subestima."
  },

  // ══════════ UFSJ · Editais CPD 020 a 031/2026 (MS · inscrição fecha em 04/10) ══════════
  {
    id: "ufsj-2026", logo: "ufsj.png",
    uf: "MG", sigla: "UFSJ",
    instituicao: "Universidade Federal de São João del-Rei",
    nivel: "Magistério Superior",
    numero_edital: "Editais CPD nº 020/2026 a 031/2026",
    areas: "Engenharia Química, Recursos Florestais, Projetos Mecânicos, Música, Anatomia, Clínica Médica, Engenharia da Computação e Psicologia clínica e educacional",
    vagas: "12 vagas (4 reservadas a pretos, pardos e indígenas, 2 para PcD)",
    campi: "São João del-Rei, Divinópolis, Ouro Branco e Sete Lagoas (MG)",
    titulacao: "Doutorado na maioria. Algumas vagas de Medicina aceitam graduação com especialização",
    remuneracao: "R$ 5.149,74 a R$ 13.753,96, conforme titulação e regime",
    regime: "40 horas, com dedicação exclusiva em parte das vagas",
    banca: "SIGRH/UFSJ",
    link_oficial: "https://sigrh.ufsj.edu.br/sigrh/public/home.jsf",
    inscricao: { inicio: "2026-09-03", fim: "2026-10-04", situacao: "aberta", taxa: "R$ 128,74 a R$ 343,85, conforme a vaga. Isenção de 03 a 08/09" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma específico de cada edital de área, publicado após a homologação das inscrições" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Sai no cronograma específico de cada edital de área" }, detalhe: {} },
      { nome: "Defesa de Plano de Trabalho", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova Prática (em algumas áreas)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Prazo de inscrição folgado, quase um mês. A defesa de plano de trabalho é etapa própria aqui: prepare o documento junto com o plano de aula, não deixe para depois."
  },

  // ══════════ UFLA · Edital PROGEPE 127/2026 (EBTT · Colégio de Aplicação · sorteio 27/09 · didática a partir de 28/09) ══════════
  {
    id: "ufla-127-2026", logo: "ufla.png",
    uf: "MG", sigla: "UFLA",
    instituicao: "Universidade Federal de Lavras, Colégio de Aplicação CAp NEDI",
    nivel: "EBTT",
    numero_edital: "Edital PROGEPE nº 127/2026, com Edital Complementar nº 136/2026",
    areas: "Docência na educação básica do Colégio de Aplicação, com foco em educação infantil e anos iniciais",
    vagas: "8 vagas (5 ampla concorrência, 2 pretos e pardos, 1 indígena, 1 quilombola, 1 PcD)",
    campi: "Lavras/MG",
    titulacao: "Graduação em Pedagogia, Normal Superior ou Educação Infantil, mais mestrado em Educação",
    remuneracao: "Base de R$ 6.180,85, chegando a R$ 13.288,83 com doutorado e incentivo à qualificação",
    regime: "40 horas com dedicação exclusiva",
    banca: "PROGEPE/UFLA, com apoio da DIPS na aplicação da prova escrita",
    link_oficial: "https://progepe.ufla.br/index.php/concursos/concurso-docente/257-26/16941-ebtt",
    inscricao: { inicio: "2026-07-10", fim: "2026-08-10", situacao: "encerrada", taxa: "R$ 200,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-08-30", nota: "Já realizada. Resultado ainda não publicado" },
        detalhe: { duracao: "3 horas", formato: "Dissertativa, de 3 a 4 páginas", nota_minima: "70 de 100 pontos" } },
      { nome: "Sorteio do tema da prova didática", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-27", nota: "Previsto para as 8h, em local divulgado na página do edital. A UFLA pode alterar data, horário e local" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-28", nota: "A partir de 28/09, no mínimo 24 horas após o sorteio. Continua nos dias seguintes se o número de aprovados na escrita exigir" },
        detalhe: { duracao: "Aula de 50 minutos sobre tema sorteado",
                   nota_minima: "70 de 100 pontos",
                   sorteio: "Sim. Temas e bibliografia já foram publicados na página do edital" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "exata", valor: "2026-09-26", nota: "Envio do currículo pelo sistema até 23h59 do dia anterior ao sorteio" }, detalhe: {} }
    ],
    observacao: "O sorteio do tema está previsto para 27/09, às 8h, e a aula acontece a partir de 28/09. O currículo vai pelo sistema até 26/09. Os temas e a bibliografia já estão publicados, então quem fez a escrita de 30/08 deve montar os planos agora, sem esperar o resultado."
  },

  // ══════════ IFSULDEMINAS · Edital 188/2026 (EBTT · objetiva 13/09 · didática 31/10 e 01/11) ══════════
  {
    id: "ifsuldeminas-188-2026", logo: "ifsuldeminas.png",
    uf: "MG", sigla: "IFSULDEMINAS", sigla_selo: "IF SUL DE MINAS",
    instituicao: "Instituto Federal do Sul de Minas Gerais",
    nivel: "EBTT",
    numero_edital: "Edital nº 188/2026, com 1ª e 2ª retificações",
    areas: "Diversas áreas. Consulte o quadro de vagas do edital",
    vagas: "19 vagas para Professor EBTT + cadastro de reserva",
    campi: "Vários campi do sul de Minas (provas em Pouso Alegre/MG)",
    titulacao: "Formação superior compatível com a área de atuação",
    remuneracao: "Até R$ 13.753,96, conforme titulação",
    regime: "40h semanais, dedicação exclusiva",
    banca: "FUNDATEC",
    link_oficial: "https://portal.ifsuldeminas.edu.br/index.php/concursos-publicos/concurso-para-docentes/abertos/7580-edital-188-2026",
    inscricao: { inicio: "2026-07-31", fim: "2026-08-20", situacao: "encerrada", taxa: "R$ 200,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Objetiva", tipo: "objetiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-13", nota: "Comunicado nº 1 de 21/08: a prova passou a ser em um único dia, domingo, em dois turnos" },
        detalhe: { questoes: "50 questões", duracao: "3 horas",
                   local: "Pouso Alegre/MG, em dois locais: Escola Estadual Virgília Paschoal e IFSULDEMINAS Campus Pouso Alegre. Manhã: portões às 8h, fecham às 8h45, início às 9h. Tarde: portões às 13h30, fecham às 14h15, início às 14h30. Sala no Comprovante Definitivo de Inscrição, em suap.ifsuldeminas.edu.br/concurso",
                   materias: [
                     { nome: "Língua Portuguesa", questoes: 10, pontos: "até 20 pontos (peso 2)" },
                     { nome: "Legislação aplicada ao Serviço Público", questoes: 10, pontos: "até 20 pontos (peso 2)" },
                     { nome: "Conhecimentos Específicos", questoes: 30, pontos: "até 60 pontos (peso 2)" }
                   ] } },
      { nome: "Resultado final da prova objetiva", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-13", nota: "Gabarito preliminar em 14/09" }, detalhe: {} },
      { nome: "Convocação para a prova didática", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-14" }, detalhe: {} },
      { nome: "Prova de Desempenho Didático", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-31", fim: "2026-11-01", nota: "Cronograma retificado. A prova didática passou de 24 e 25/10 para 31/10 e 01/11" },
        detalhe: { duracao: "Aula de 15 a 20 minutos, com arguição posterior de até 10 minutos",
                   sorteio: "Sim. Tema sorteado 24 horas antes da apresentação",
                   nota_minima: "60 pontos (abaixo disso, elimina)",
                   arguicao: "Sim, até 10 minutos após a aula",
                   modalidade: "Presencial em Pouso Alegre/MG (remota apenas em caso de força maior)",
                   criterios: "Planejamento, comunicação, domínio do conteúdo, metodologia de ensino, organização da aula, gestão do tempo e avaliação da aprendizagem",
                   ordem: "A ordem de apresentação segue a classificação na prova objetiva" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-31", fim: "2026-11-01", nota: "Entrega junto com a prova didática" },
        detalhe: { criterios: "Títulos acadêmicos, experiência profissional na área e experiência docente (máx. 100 pontos)" } },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2026-12-10", nota: "Homologação em 11/12/2026" }, detalhe: {} }
    ],
    observacao: "A prova objetiva virou dia único, 13/09, em dois turnos. Confira o seu turno e a sua sala no Comprovante Definitivo de Inscrição. Aula curta, de 15 a 20 minutos, com tema sorteado 24h antes: formato que exige recorte muito preciso do conteúdo, e ainda tem arguição de até 10 minutos depois."
  },

  // ══════════ IFSC · Edital 01/2026 (EBTT · escrita 27/09 · didática 23 a 28/11) ══════════
  {
    id: "ifsc-01-2026", logo: "ifsc.png",
    uf: "SC", sigla: "IFSC",
    instituicao: "Instituto Federal de Santa Catarina",
    nivel: "EBTT",
    numero_edital: "Edital nº 01/2026, com retificações de 14/08 e 19/08",
    areas: "24 áreas de conhecimento: Administração, Artes, Automação Industrial, Física, Informática, Matemática, Fabricação Mecânica, Química, entre outras",
    vagas: "46 vagas de provimento imediato + cadastro de reserva",
    campi: "Campi de todo o estado de Santa Catarina",
    titulacao: "Formação superior conforme a área (titulação mínima varia por vaga)",
    remuneracao: "R$ 6.180,86 a R$ 13.288,85 + auxílio-alimentação de R$ 1.192",
    regime: "40h semanais, dedicação exclusiva",
    banca: "FAURGS",
    link_oficial: "https://portalfaurgs.com.br/concursosFaurgs/emandamento/1277-012026ifsc-institutofederaldesantacatarina",
    inscricao: { inicio: "2026-07-20", fim: "2026-08-17", situacao: "encerrada", taxa: "R$ 300,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Homologação final das inscrições e convocação às provas", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-15" }, detalhe: {} },
      { nome: "Prova Objetiva", tipo: "objetiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-27", nota: "Turno da tarde, conforme comunicado da FAURGS. O cronograma da banca ainda exibe a linha como data provável" },
        detalhe: { questoes: "50 questões de múltipla escolha (5 alternativas, 1 correta). Sem desconto por erro.",
                   local: "Preferencialmente Chapecó, Florianópolis e Joinville",
                   nota_minima: "Mínimo de 55 pontos E acerto mínimo por bloco",
                   materias: [
                     { nome: "Conhecimentos Gerais (Língua Portuguesa, Legislação e Contexto Histórico da Educação Profissional, Conhecimentos Pedagógicos)", questoes: 20, pontos: "" },
                     { nome: "Conhecimentos Específicos da área", questoes: 30, pontos: "" }
                   ] } },
      { nome: "Prova Discursiva", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-27", nota: "Aplicada no mesmo dia da objetiva, turno da tarde" },
        detalhe: { formato: "Questão única, igual para todas as áreas docentes",
                   local: "Preferencialmente Chapecó, Florianópolis e Joinville" } },
      { nome: "Prova de Desempenho Didático", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-11-23", fim: "2026-11-28" },
        detalhe: { duracao: "Consulte o Anexo I do edital consolidado",
                   nota_minima: "70 pontos",
                   modalidade: "Presencial, perante banca examinadora",
                   sorteio: "Consulte o item 8 do edital consolidado",
                   convocados: "Retificação de 19/08 unificou o quantitativo de convocados: 1 vaga convoca 6, 2 vagas convocam 11, 3 vagas convocam 17" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Após a prova didática, com envio on-line pelo site da FAURGS" },
        detalhe: { criterios: "Formulário de Relação de Títulos com envio eletrônico (JPG, JPEG ou PDF, até 5 MB por arquivo)" } },
      { nome: "Homologação do resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2027-01-13" }, detalhe: {} }
    ],
    observacao: "Nota mínima alta na prova didática, 70 pontos. A prova escrita reúne objetiva e discursiva no mesmo dia, 27/09, no turno da tarde. Duas retificações em agosto mudaram o número de convocados para a didática, então confira a sua posição depois do resultado da escrita."
  },

  // ══════════ UFU · Editais 93 e 94/2026 (EBTT e MS · últimas didáticas em 16 e 18/09) ══════════
  {
    id: "ufu-93-94-2026", logo: "ufu.png", uf: "MG", sigla: "UFU",
    instituicao: "Universidade Federal de Uberlândia", nivel: "EBTT e Magistério Superior",
    numero_edital: "Editais PROGEP nº 93/2026 (EBTT) e nº 94/2026 (Magistério Superior), com complementares 95 a 100/2026",
    areas: "Ciências da Natureza e Educação Física na ESEBA (EBTT). Engenharia Elétrica e Telecomunicações e duas vagas na Faculdade de Medicina: Gastroenterologia e Pneumologia (Magistério Superior)",
    vagas: "1 vaga no Edital 93/2026 (ESEBA) e 3 vagas ativas no Edital 94/2026 (Endocrinologia e Psiquiatria ficaram desertas)",
    campi: "Santa Mônica (Uberlândia), ESEBA, Faculdade de Medicina",
    titulacao: "Licenciatura plena em Ciências Biológicas para a vaga da ESEBA. Doutorado, em regra, para o Magistério Superior",
    remuneracao: "Até R$ 13.288,85 + auxílio-alimentação", regime: "Dedicação exclusiva na FEELT e na ESEBA. 40 horas nas vagas da Faculdade de Medicina",
    banca: "PROGEP/UFU",
    link_oficial: "https://www.portalselecao.ufu.br/servicos/Edital/listar/concursos",
    inscricao: { inicio: "2026-06-09", fim: "2026-06-24", situacao: "encerrada", taxa: "R$ 320,00, com pagamento até 25/06" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-08-02", nota: "Das 10h às 14h, comum aos editais complementares 95 a 100/2026. Já realizada" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-09-16", fim: "2026-09-18", nota: "Faltam só as da Faculdade de Medicina: Pneumologia (100/2026) em 16/09 às 8h30, com sorteio em 15/09, e Gastroenterologia (98/2026) em 18/09 às 8h30, com sorteio em 17/09. FEELT (03/09) e ESEBA (10/09) já realizadas. Endocrinologia (95/2026) e Psiquiatria (99/2026) ficaram desertas" },
        detalhe: { duracao: "Aula de 40 a 50 minutos",
                   sorteio: "Sim. Tema sorteado com no mínimo 24 e no máximo 36 horas de antecedência, junto com o sorteio da ordem de apresentação",
                   arguicao: "No Edital 94/2026 (Magistério Superior), arguição da banca de até 30 minutos",
                   modalidade: "Sala virtual no Edital 100/2026 (Pneumologia)",
                   plano_de_aula: "No 98/2026, até 10 minutos antes da aula. No 100/2026, por e-mail até 16/09 às 8h30" } },
      { nome: "Análise de Títulos e Experiência Profissional", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova Prática, Oral ou Defesa de Projeto (quando previsto)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Depende do edital complementar" }, detalhe: {} }
    ],
    observacao: "Restam duas aulas, ambas na Faculdade de Medicina: Pneumologia em 16/09 e Gastroenterologia em 18/09. O tema sai com 24 a 36 horas de antecedência e a aula é de 40 a 50 minutos, com arguição de até 30 minutos. Cronogramas em portalselecao.ufu.br."
  },

  // ══════════ URCA · Edital 02/2026-GR (MS · escrita 18/10 · didática 13 a 15/11) ══════════
  {
    id: "urca-2026", logo: "urca.png", uf: "CE", sigla: "URCA",
    instituicao: "Universidade Regional do Cariri", nivel: "Magistério Superior",
    numero_edital: "Edital nº 02/2026-GR (DOE de 22/06/2026), com Corrigenda nº 01",
    areas: "Diversos setores de estudo", vagas: "26 vagas",
    campi: "Crato, Juazeiro do Norte, Iguatu, Campos Sales e Missão Velha",
    titulacao: "Graduação + titulação conforme a classe", remuneracao: "Conforme a classe (estatutário estadual)",
    regime: "Regime estatutário estadual", banca: "PROGRAD/URCA",
    link_oficial: "https://www.urca.br/prograd/concurso-publico-para-professor-efetivo-da-urca-edital-no-02-2026-gr/",
    inscricao: { inicio: "2026-07-22", fim: "2026-08-22", situacao: "encerrada" },
    detalhamento: "completo",
    etapas: [
      { nome: "Divulgação das bancas", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-18", nota: "Impugnação em 22 e 23/09, resultado em 29/09" }, detalhe: {} },
      { nome: "Divulgação do local da prova escrita", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-08" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "exata", valor: "2026-10-18", nota: "Resultado definitivo em 09/11" },
        detalhe: { formato: "Consulte o edital para o formato e a lista de pontos" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-11-13", fim: "2026-11-15", nota: "Resultado final da didática em 26/11" },
        detalhe: { duracao: "Aula de 50 a 60 minutos. Apresentar por menos de 50 minutos ou passar de 60 prejudica a nota",
                   sorteio: "Sim. Tema sorteado com 24 horas de antecedência",
                   nota_minima: "6,0 pontos",
                   criterios: "Inclui a utilização de recursos didáticos, que vale até 1 ponto na composição da nota",
                   modalidade: "Presencial, no campus da vaga" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-11-12", fim: "2026-11-15", nota: "Títulos recebidos junto com a prova didática" },
        detalhe: { criterios: "Análise do Currículo Lattes e documentos comprobatórios, conforme a Resolução nº 08/2025-CEPE da URCA. Considera, entre outros, a participação em bancas examinadoras." } },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2026-12-16" }, detalhe: {} }
    ],
    observacao: "Cronograma novo, publicado em 20/08/2026, substituiu o anterior. A prova escrita é em 18/10 e a didática de 13 a 15/11, com tema sorteado 24 horas antes. Universidade estadual do Ceará, regime estatutário estadual."
  },

  // ══════════ IFMT · Edital 03/2026 (EBTT · sorteio dos temas 14/10 · didática 29/10 a 29/11) ══════════
  {
    id: "ifmt-03-2026", logo: "ifmt.png", uf: "MT", sigla: "IFMT",
    instituicao: "Instituto Federal de Mato Grosso", nivel: "EBTT",
    numero_edital: "Edital nº 03/2026",
    areas: "Administração, Informática, Física, Matemática, Química, Manutenção de Aeronaves, Medicina Veterinária, Português/Espanhol, Zootecnia",
    vagas: "21 vagas",
    campi: "Alta Floresta, Colniza, Confresa, Canarana, Guarantã do Norte, Juína, Pontes e Lacerda, Primavera do Leste e Sorriso",
    titulacao: "Nível superior na área", remuneracao: "R$ 7.589,19 a R$ 14.945,96",
    regime: "40h com dedicação exclusiva", banca: "Comissão própria do IFMT",
    link_oficial: "https://seletivo.ifmt.edu.br/edital/visualizar/173/",
    inscricao: { inicio: "2026-07-20", fim: "2026-08-06", situacao: "encerrada", taxa: "R$ 160,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Objetiva", tipo: "objetiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-08-30", nota: "Das 14h às 18h. Já realizada" },
        detalhe: { questoes: "50 questões de múltipla escolha, com 5 alternativas e apenas 1 correta",
                   pontuacao: "0 a 100 pontos", duracao: "4 horas (14h às 18h)",
                   local: "Cuiabá e Colniza (MT), podendo haver municípios vizinhos. O candidato escolhe o local na inscrição.",
                   nota_minima: "70 pontos para ser convocado à prova de desempenho didático, respeitada a ordem de classificação" } },
      { nome: "Sorteio público dos temas da prova didática", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-14", nota: "Às 14h30, no Auditório da Reitoria em Cuiabá, com transmissão ao vivo no canal do IFMT no YouTube" }, detalhe: {} },
      { nome: "Prova de Desempenho Didático", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-29", fim: "2026-11-29", nota: "Agendada por candidato dentro deste período. Temas sorteados em 14/10" },
        detalhe: { duracao: "Aula expositiva avaliada pela banca examinadora. Consulte o edital para o tempo exato.",
                   modalidade: "Presencial em Cuiabá, podendo ocorrer em municípios vizinhos",
                   nota_minima: "Só é convocado quem tiver ao menos 70 pontos na prova objetiva",
                   sorteio: "Sorteio público em 14/10, transmitido ao vivo. Confira a regra no edital" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Documentos enviados em PDF no ato da inscrição" },
        detalhe: { criterios: "Envio em ambiente virtual pelo sistema seletivo.ifmt.edu.br, durante a inscrição" } },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2026-12-23", nota: "Publicação no Diário Oficial da União em 29/12/2026" }, detalhe: {} }
    ],
    observacao: "O sorteio dos temas é público, em 14/10, com transmissão ao vivo. Entre o sorteio e a aula há de duas a seis semanas, conforme o seu agendamento: é uma das janelas de preparação mais generosas do calendário."
  },

  // ══════════ UFPE · Edital 08/2026 (MS · provas entre 08 e 30/10) ══════════
  {
    id: "ufpe-08-2026", logo: "ufpe.png", uf: "PE", sigla: "UFPE",
    instituicao: "Universidade Federal de Pernambuco", nivel: "Magistério Superior",
    numero_edital: "Edital nº 08/2026",
    areas: "Diversas áreas dos centros acadêmicos",
    vagas: "41 vagas", campi: "Recife, Caruaru e Vitória de Santo Antão",
    titulacao: "Doutorado ou mestrado conforme a vaga",
    remuneracao: "R$ 3.399,47 (20h) a R$ 13.288,85 (40h DE)",
    regime: "20h semanais ou 40h com dedicação exclusiva", banca: "SigRH/UFPE",
    link_oficial: "https://www.ufpe.br/progepe/concursos/concursos-em-andamento",
    inscricao: { inicio: "2026-07-18", fim: "2026-08-16", situacao: "encerrada" },
    periodo_provas: { inicio: "2026-10-08", fim: "2026-10-30", nota: "Prova escrita entre 08 e 30/10; demais etapas em seguida." },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-08", fim: "2026-10-30", nota: "Cronograma divulgado por cada unidade acadêmica" },
        detalhe: { formato: "Questão discursiva sobre um ponto sorteado de uma lista de 10 temas divulgada previamente",
                   duracao: "Até 4 horas", nota_minima: "7,0",
                   local: "Avançam para as etapas seguintes apenas os 8 melhores classificados por vaga, respeitados os empates" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-08", fim: "2026-10-30", nota: "Após a prova escrita, no cronograma da sua unidade" },
        detalhe: { duracao: "Aula expositiva de 50 a 60 minutos perante a comissão examinadora",
                   sorteio: "Sim. O tema sai da mesma lista divulgada previamente, excluído o que já caiu na prova escrita. A presença no sorteio não é obrigatória, o resultado pode ser acompanhado pelo SIGRH.",
                   nota_minima: "7,0",
                   arguicao: "O candidato entrega o plano de aula antes da apresentação e pode passar por arguição da banca",
                   criterios: "Plano de aula, cumprimento do tempo, domínio do conteúdo e comunicação",
                   modalidade: "Presencial, na unidade acadêmica da vaga" } },
      { nome: "Defesa de Memorial", tipo: "memorial", carater: "Eliminatória",
        data: { tipo: "periodo", valor: "2026-10-08", fim: "2026-10-30" },
        detalhe: { formato: "Etapa obrigatória para Magistério Superior. O memorial é enviado pelo SIGRH no prazo do cronograma.", nota_minima: "7,0" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-08", fim: "2026-10-30" },
        detalhe: { criterios: "Análise curricular do candidato" } },
      { nome: "Etapas adicionais (só em algumas áreas)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Indicadas nas Informações Complementares de cada área" },
        detalhe: { formato: "Prova Didático-Prática (eliminatória) e Defesa de Plano de Trabalho (classificatória), quando a unidade exigir" } }
    ],
    observacao: "Aprovação exige nota mínima 7,0 em cada etapa eliminatória. A nota final é a média ponderada das provas. Homologação prevista para janeiro de 2027."
  },

  // ══════════ UFBA · Edital 06/2026 (MS · provas de 03/09 a 06/11) ══════════
  {
    id: "ufba-06-2026", logo: "ufba.png",
    uf: "BA", sigla: "UFBA",
    instituicao: "Universidade Federal da Bahia",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 06/2026",
    areas: "Engenharias (Civil, Elétrica, Produção, Controle e Automação), Medicina, Enfermagem, Contabilidade, Direito, Química, entre outras",
    vagas: "37 vagas (24 ampla concorrência, 2 PcD, 9 negros, 1 indígena, 1 quilombola)",
    campi: "Salvador e Vitória da Conquista",
    titulacao: "Graduação + pós-graduação conforme a vaga (classe A, Professor Assistente)",
    remuneracao: "R$ 3.198,59 a R$ 13.753,96, conforme carga horária e titulação",
    regime: "Dedicação exclusiva, 40h ou 20h semanais",
    banca: "PRODEP/UFBA",
    link_oficial: "https://concursos.ufba.br/docentes",
    inscricao: { inicio: "2026-06-25", fim: "2026-07-27", situacao: "encerrada" },
    periodo_provas: { inicio: "2026-09-03", fim: "2026-11-06",
      nota: "Os cronogramas por área já começaram a ser publicados. Consulte concursos.ufba.br/docentes para a data da sua área, divulgada com antecedência mínima de 30 dias." },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Teórico-Prática ou Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória · peso 3",
        data: { tipo: "periodo", valor: "2026-09-03", fim: "2026-11-06", nota: "Data da sua área divulgada com 30 dias de antecedência" },
        detalhe: { formato: "Avalia competência técnica, capacidade analítica e expressão escrita",
                   nota_minima: "7,0", local: "Na própria UFBA" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Classificatória · peso 3",
        data: { tipo: "periodo", valor: "2026-09-03", fim: "2026-11-06", nota: "Data da sua área divulgada com 30 dias de antecedência" },
        detalhe: { duracao: "Consulte o edital da sua área",
                   modalidade: "Presencial, na própria UFBA",
                   peso: "Peso 3, o mesmo peso da prova escrita",
                   sorteio: "Consulte o edital da sua área" } },
      { nome: "Defesa de Memorial", tipo: "memorial", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-09-03", fim: "2026-11-06" },
        detalhe: { formato: "Defesa da trajetória acadêmica e profissional perante a banca" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória · peso 2",
        data: { tipo: "periodo", valor: "2026-09-03", fim: "2026-11-06" },
        detalhe: { criterios: "Formação acadêmica e produção do candidato" } }
    ],
    observacao: "A prova didática tem peso 3, o mesmo peso da prova escrita. Em caso de empate, o desempate considera primeiro a prova escrita, depois a didática."
  },

  // ══════════ UFTM · Edital 28/2026 (EBTT · escrita 20/09 · didática 09/10 a 17/11) ══════════
  {
    id: "uftm-28-2026", logo: "uftm.png", uf: "MG", sigla: "UFTM",
    instituicao: "Universidade Federal do Triângulo Mineiro", nivel: "EBTT",
    numero_edital: "Edital nº 28/2026, com retificações 01 e 02",
    areas: "Centro de Educação Profissional (CEFORES), em 4 lotações: Morfologia, Anatomia Patológica e Patologia Clínica (Lotação 01), Radiologia (Lotação 02), Odontologia, Clínica Odontológica e Materiais Odontológicos (Lotação 03) e Enfermagem (Lotação 04)",
    vagas: "4 vagas",
    campi: "Uberaba/MG, Centro de Educação Profissional CEFORES", titulacao: "Conforme a lotação",
    remuneracao: "R$ 6.397,19 (Nível 1, Classe A) em 40h com dedicação exclusiva",
    regime: "40 horas com dedicação exclusiva",
    banca: "Comissão própria da UFTM",
    link_oficial: "https://sistemas.uftm.edu.br/integrado/sistemas/pub/publicacao.html?secao=101",
    inscricao: { inicio: "2026-07-25", fim: "2026-08-13", situacao: "encerrada", taxa: "R$ 240,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Divulgação dos locais de prova e ensalamento", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-11", nota: "Prazo limite, conforme a Retificação 01" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "exata", valor: "2026-09-20", nota: "Data alterada pela Retificação 01 de 23/07. Era 13/09 e passou para 20/09. Resultado em 05/10 às 17h" },
        detalhe: { formato: "Temas na Relação de Temas publicada em 20/07 (Anexo I), comum às provas escrita, didática e prática" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-09", fim: "2026-11-17", nota: "Datas publicadas em 28/08, por lotação e por turma. Cada candidato tem dia e horário próprios. Resultado em 23/11 às 17h" },
        detalhe: { sorteio: "Sim. O tema é sorteado no dia anterior à aula, com confinamento do candidato até a apresentação",
                   modalidade: "Presencial, no Centro Educacional da UFTM em Uberaba. A Retificação 02 de 25/08 alterou a modalidade de execução para presencial ou híbrida",
                   ordem: "Os candidatos são divididos em turmas, com sorteio e aula em dias sucessivos. Na Lotação 01 são 8 turmas, de 09/10 a 17/11",
                   duracao: "Consulte o edital 28/2026" } },
      { nome: "Prova Prática (somente Radiologia, Lotação 02)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Consulte o documento da Lotação 02, publicado em 28/08" }, detalhe: {} },
      { nome: "Avaliação de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Atenção à mudança de data: a prova escrita passou de 13/09 para 20/09 pela Retificação 01. As datas das provas didáticas saíram em 28/08, por lotação e por turma, entre 09/10 e 17/11. O formato é duro: o tema é sorteado no dia anterior e o candidato fica confinado até a hora da aula, sem acesso a material externo."
  },

  // ══════════ UFS · Edital 008/2026 (MS e EBTT · provas de 21/09 a 11/01) ══════════
  {
    id: "ufs-08-2026", logo: "ufs.png", uf: "SE", sigla: "UFS",
    instituicao: "Universidade Federal de Sergipe", nivel: "Magistério Superior",
    numero_edital: "Edital nº 008/2026",
    areas: "Magistério Superior e EBTT, em diversas áreas", vagas: "8 vagas",
    campi: "Lagarto, São Cristóvão e Aracaju",
    titulacao: "Conforme a vaga", remuneracao: "Conforme titulação e regime",
    regime: "Conforme a vaga", banca: "CMOP/UFS",
    link_oficial: "https://cmop.ufs.br/conteudo/79778",
    inscricao: { inicio: "2026-07-20", fim: "2026-08-18", situacao: "encerrada", taxa: "R$ 100,00 (graduação) a R$ 200,00 (doutorado)" },
    periodo_provas: { inicio: "2026-09-21", fim: "2027-01-11", nota: "Janela oficial dentro da qual as bancas devem realizar as provas. Não é data de prova." },
    detalhamento: "basico",
    etapas: [
      { nome: "Relação definitiva de inscritos", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-02", nota: "Já publicada" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "nao_divulgada", nota: "Calendário divulgado por departamento, dentro da janela de 21/09 a 11/01" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "O calendário é divulgado por cada departamento, com no mínimo 15 dias de antecedência do início das provas. Nenhum foi publicado até 11/09" },
        detalhe: { duracao: "50 minutos, com tolerância de 5 minutos para mais ou para menos",
                   sorteio: "Sim. Tema sorteado com 24 horas de antecedência" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Projeto de Pesquisa (para doutores)", tipo: "outra", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "As provas podem cair a qualquer momento entre 21/09/2026 e 11/01/2027, conforme o departamento definir. Acompanhe cmop.ufs.br, porque o aviso pode vir com pouca antecedência."
  },

  // ══════════ UNIFESP · edital do DOU de 17/06/2026 (MS e EBTT) ══════════
  {
    id: "unifesp-2026", logo: "unifesp.png", uf: "SP", sigla: "UNIFESP",
    instituicao: "Universidade Federal de São Paulo", nivel: "Magistério Superior",
    numero_edital: "Edital publicado no DOU de 17/06/2026",
    areas: "Diversas áreas (Magistério Superior e EBTT)", vagas: "41 vagas",
    campi: "Diadema, Baixada Santista (Santos), São José dos Campos, Osasco, Guarulhos, São Paulo e Núcleo Educacional Infantil Paulistinha",
    titulacao: "Doutorado (requisitos específicos por vaga)",
    remuneracao: "Conforme regime (20h, 40h ou DE)", regime: "20h, 40h ou dedicação exclusiva",
    banca: "Própria (portal de concursos da UNIFESP)",
    link_oficial: "https://concursos.unifesp.br/",
    inscricao: { inicio: "2026-06-22", fim: "2026-07-22", situacao: "encerrada" },
    periodo_provas: { inicio: "2026-10-01", fim: "2026-12-31", nota: "Provas previstas entre outubro e dezembro de 2026." },
    detalhamento: "basico",
    etapas: [
      { nome: "Envio de documentação on-line", tipo: "outra", carater: "",
        data: { tipo: "periodo", valor: "2026-07-27", fim: "2026-08-05", nota: "Já realizado" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "periodo", valor: "2026-10-01", fim: "2026-12-31", nota: "Data por área a divulgar" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-01", fim: "2026-12-31", nota: "Data por área a divulgar" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Acompanhe o portal de concursos da UNIFESP para a data da sua área."
  },

  // ══════════ UFRGS · Edital 08/2026 (MS · cronograma por área) ══════════
  {
    id: "ufrgs-08-2026", logo: "ufrgs.png", uf: "RS", sigla: "UFRGS",
    instituicao: "Universidade Federal do Rio Grande do Sul", nivel: "Magistério Superior",
    numero_edital: "Edital nº 08/2026",
    areas: "Artes, Educação, Engenharia, Geociências, Saúde, Agrárias, Humanidades e Química",
    vagas: "15 vagas", campi: "Porto Alegre e demais unidades da UFRGS",
    titulacao: "Doutorado", remuneracao: "R$ 13.753,96", regime: "Dedicação exclusiva (40h)",
    banca: "PROGESP/UFRGS",
    link_oficial: "https://www.ufrgs.br/progesp/edital-08-2026-concurso-publico-docente/",
    inscricao: { inicio: "2026-06-10", fim: "2026-06-24", situacao: "encerrada", taxa: "R$ 262,00" },
    detalhamento: "basico",
    etapas: [
      { nome: "Ato de Instalação", tipo: "outra", carater: "Comparecimento obrigatório",
        data: { tipo: "nao_divulgada", nota: "Cronograma por área" }, detalhe: {} },
      { nome: "Prova Escrita (1ª fase)", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma por área a divulgar" },
        detalhe: { nota_minima: "7,0" } },
      { nome: "Prova Didática (2ª fase)", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Cronograma por área a divulgar" },
        detalhe: { duracao: "Consulte o edital da sua área",
                   formato: "Avalia a capacidade de planejamento e de condução de aula",
                   nota_minima: "7,0",
                   peso: "No desempate, a prova didática é o primeiro critério considerado, à frente de títulos e da prova escrita",
                   modalidade: "Presencial, na unidade da vaga" } },
      { nome: "Defesa da Produção Intelectual", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" },
        detalhe: { formato: "Defesa da produção acadêmica perante a banca" } },
      { nome: "Exame de Títulos e Trabalhos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova Prática (quando aplicável à área)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Apenas em algumas áreas" }, detalhe: {} }
    ],
    observacao: "Nota mínima 7,0 nas etapas centrais. No desempate vale primeiro a nota da prova didática. Os cronogramas são publicados por área na PROGESP e o não comparecimento a qualquer prova elimina o candidato."
  },

  // ══════════ IFMG · Edital 607/2026 (EBTT · inscrição até 29/09 · escrita 29/11 · didática 15 a 19/02/2027) ══════════
  {
    id: "ifmg-2026", logo: "ifmg.png", uf: "MG", sigla: "IFMG",
    instituicao: "Instituto Federal de Minas Gerais", nivel: "EBTT",
    numero_edital: "Edital nº 607/2026, com Retificações 01 a 03 de 04/09/2026 e 04 de 09/09/2026",
    areas: "Direito (Civil e Processual Civil, Empresarial e do Trabalho, Filosofia e Sociologia Jurídica) e Língua Portuguesa, Literaturas, Redação e Libras",
    vagas: "4 vagas (3 ampla concorrência, 1 pessoas negras)",
    campi: "Congonhas (Língua Portuguesa, Literaturas, Redação e Libras), Ribeirão das Neves (Direito) e Arcos (2 vagas de Direito)",
    titulacao: "Nível superior na área. Para a vaga de Congonhas, após a Retificação 02: Licenciatura em Letras com habilitação em Português/Libras, ou Licenciatura em Letras com habilitação em Língua Portuguesa e certificado PROLIBRAS. Ingresso na classe A, nível 1",
    remuneracao: "Vencimento básico de R$ 6.397,19 + R$ 1.192,00 de auxílio-alimentação (R$ 7.589,19), chegando a R$ 14.945,96 com doutorado",
    regime: "40 horas semanais com dedicação exclusiva",
    banca: "Comissão própria do IFMG",
    link_oficial: "https://portal.concursos.ifmg.edu.br/edital/ver/165",
    inscricao: { inicio: "2026-09-09", fim: "2026-09-29", situacao: "aberta", taxa: "R$ 250,00. Inscrição até 18h de 29/09. Prazo de isenção encerrado em 10/09" },
    detalhamento: "completo",
    etapas: [
      { nome: "Homologação final das inscrições", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Consulte o cronograma retificado em 04/09 no portal de concursos do IFMG" }, detalhe: {} },
      { nome: "Divulgação dos locais de prova", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-15" }, detalhe: {} },
      { nome: "Prova Objetiva e Dissertativa", tipo: "objetiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-11-29", nota: "Data alterada pela Retificação nº 1 de 04/09. Antes era 25/10" },
        detalhe: { formato: "Prova objetiva e dissertativa aplicadas no mesmo dia" } },
      { nome: "Convocação e entrega do memorial e do material da prova didática", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada", nota: "Antes da prova didática. As datas novas estão no cronograma retificado em 04/09" }, detalhe: {} },
      { nome: "Prova de Desempenho Didático", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2027-02-15", fim: "2027-02-19", nota: "Período alterado pela Retificação nº 1 de 04/09. Antes era 11 a 15/01/2027" },
        detalhe: { duracao: "Consulte o corpo do edital 607/2026",
                   sorteio: "Consulte o corpo do edital 607/2026",
                   modalidade: "Presencial",
                   plano_de_aula: "Memorial e material entregues antes da aula, no prazo do cronograma retificado" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "No cronograma original, junto com a prova didática. Confira o cronograma retificado" },
        detalhe: { criterios: "100 pontos. Títulos acadêmicos até 50 (doutorado 25, mestrado 15, especialização 5, aperfeiçoamento 5, conforme a Retificação 04), ensino, pesquisa e extensão até 25, produção acadêmica até 20, experiência profissional até 5" } },
      { nome: "Resultado final homologado", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2027-03-25", nota: "Previsão de publicação do resultado final e homologação" }, detalhe: {} }
    ],
    observacao: "Inscrição aberta até 29/09. A retificação de 04/09 empurrou a prova escrita para 29/11 e a didática para 15 a 19/02/2027, com entrega de memorial antes da aula. São quase três meses entre a escrita e a aula: tempo de sobra para quem começar cedo."
  },

  // ══════════ UFPE · Edital 09/2026 (MS · Centro Acadêmico do Sertão) ══════════
  {
    id: "ufpe-09-2026", logo: "ufpe.png", uf: "PE", sigla: "UFPE",
    instituicao: "Universidade Federal de Pernambuco (Centro Acadêmico do Sertão)", nivel: "Magistério Superior",
    numero_edital: "Edital nº 09/2026",
    areas: "Diferentes áreas do Centro Acadêmico do Sertão", vagas: "16 vagas",
    campi: "Sertânia/PE", titulacao: "Conforme a vaga",
    remuneracao: "Conforme regime e titulação", regime: "Conforme a vaga", banca: "SigRH/UFPE",
    link_oficial: "https://www.ufpe.br/progepe/concursos/concursos-em-andamento",
    inscricao: { inicio: null, fim: null, situacao: "consultar" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "nao_divulgada", nota: "Consulte o cronograma no portal do Progepe" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Consulte o cronograma no portal do Progepe" }, detalhe: {} },
      { nome: "Defesa de Memorial", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Edital publicado no DOU de 09/07/2026. As datas de inscrição e o cronograma precisam ser confirmados no portal oficial do Progepe."
  },

  // ══════════ UNIMONTES · Editais 01 a 27/2026 (MS estadual · mais de 400 vagas · provas jan e fev/2027) ══════════
  {
    id: "unimontes-2026", logo: "unimontes.png",
    uf: "MG", sigla: "UNIMONTES", sigla_selo: "UNI MONTES",
    instituicao: "Universidade Estadual de Montes Claros",
    nivel: "Magistério Superior",
    numero_edital: "Editais nº 01/2026 a 27/2026, um por departamento",
    areas: "27 departamentos, de Ciências da Computação, Economia e História a Medicina, Odontologia, Direito, Educação, Artes e Educação Física",
    vagas: "Mais de 400 vagas no conjunto dos 27 editais",
    campi: "Montes Claros, Janaúba e demais unidades da Unimontes",
    titulacao: "Especialização, mestrado ou doutorado, conforme o nível da vaga",
    remuneracao: "R$ 3.316,79 (Nível I, especialista) · R$ 5.626,35 (Nível IV, mestre) · R$ 8.257,49 (Nível VI, doutor)",
    regime: "Estatutário estadual de Minas Gerais, 40 horas",
    banca: "Comissão própria, com banca examinadora de 3 titulares e 2 suplentes por área",
    link_oficial: "https://concurso.unimontes.br/editais-recentes/",
    inscricao: { inicio: "2026-08-24", fim: "2026-12-19", situacao: "aberta", taxa: "R$ 100,00 (especialização), R$ 150,00 (mestrado), R$ 200,00 (doutorado). As datas variam por edital: o 01/2026 e outros vão de 24/08 a 24/10, e o 07/2026 e outros de 19/10 a 19/12" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova de Conhecimentos", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2027-01-10", fim: "2027-02-21", nota: "A data varia por edital, após as retificações que adiaram a antiga data de 08/11/2026. Artes (27) em 10/01; editais 01, 04, 05, 07 e 10 em 14/02 de manhã; Letras (17) em 14/02 à tarde; Fisiopatologia (23) em 21/02 de manhã; Enfermagem (25) e Educação Física (26) em 21/02 à tarde" },
        detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Após a prova de conhecimentos do seu edital. Data, horário e local são divulgados com antecedência mínima de 30 dias" },
        detalhe: { pontuacao: "100 pontos",
                   sorteio: "Sim. Prazo mínimo de 24 horas entre o sorteio do tema e a exposição oral",
                   duracao: "Consulte o edital do seu departamento",
                   criterios: "Candidato que estiver ao mesmo tempo na lista de cota e na de ampla concorrência faz a prova didática uma única vez, e a nota vale para as duas listas" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Após a prova didática, com envio digital" }, detalhe: {} }
    ],
    observacao: "É o maior concurso docente estadual aberto no Brasil hoje, mais de 400 vagas, e o primeiro da Unimontes desde 2016. Inscrição aberta agora e prova de conhecimentos entre janeiro e fevereiro de 2027, conforme o edital: são de quatro a cinco meses de preparo, cenário raro. As 24 horas entre o sorteio e a aula definem o preparo aqui, dá para montar o plano com calma, mas não dá para improvisar repertório."
  },

  // ══════════ UFRJ · Edital 942/2026 (MS · inscrição aberta · provas a partir de 28/12) ══════════
  {
    id: "ufrj-942-2026", logo: "ufrj.png",
    uf: "RJ", sigla: "UFRJ",
    instituicao: "Universidade Federal do Rio de Janeiro",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 942, de 18 de agosto de 2026",
    areas: "Escola de Música, Departamento de Música de Conjunto, setorização Canto Coral",
    vagas: "1 vaga, reservada a pessoa preta ou parda",
    campi: "Rio de Janeiro/RJ",
    titulacao: "Doutorado em Música com temática em Canto Coral. Classe Assistente 1A",
    remuneracao: "R$ 13.753,96",
    regime: "40 horas com dedicação exclusiva",
    banca: "PR-4 e Comissão Julgadora da unidade",
    link_oficial: "https://concursos.pr4.ufrj.br/index.php/837-edital-n-942-de-18-de-agosto-de-2026",
    inscricao: { inicio: "2026-09-03", fim: "2026-09-27", situacao: "aberta", taxa: "R$ 300,00, com pagamento até 29/09. Isenção de 03 a 11/09" },
    detalhamento: "basico",
    etapas: [
      { nome: "Lista final de inscritos", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-10-08", nota: "Preliminar em 02/10" }, detalhe: {} },
      { nome: "Divulgação da banca examinadora", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-11-10", nota: "Impugnação até 21/11, banca final até 30/11" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-12-28", fim: "2027-02-26", nota: "Janela oficial das provas. A unidade divulga local e cronograma com no mínimo 30 dias de antecedência" },
        detalhe: { duracao: "Não fixada no edital. As regras remetem à Resolução CONSUNI nº 15/2020",
                   sorteio: "Não fixado no edital. Consulte a Resolução CONSUNI nº 15/2020 e o cronograma da Escola de Música" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-12-28", fim: "2027-02-26" }, detalhe: {} },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "exata", valor: "2027-04-16", nota: "Publicação no Boletim da UFRJ, conforme o Anexo III. Publicação no DOU até 04/05/2027" }, detalhe: {} }
    ],
    observacao: "Inscrição aberta agora e prova só a partir do fim de dezembro. É o maior prazo de preparo do radar. Vaga única e muito específica. O detalhamento da prova didática não está no edital, sai no cronograma da Escola de Música, publicado com 30 dias de antecedência."
  },

  // ══════════ UFSM · Edital 198/2026 (MS · período provável a partir de 13/09 · sem cronograma por área) ══════════
  {
    id: "ufsm-198-2026", logo: "ufsm.png",
    uf: "RS", sigla: "UFSM",
    instituicao: "Universidade Federal de Santa Maria",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 198/2026, publicado no DOU de 29/06/2026",
    areas: "Clínica e Cirurgia de Ruminantes, Engenharia Sanitária, Matemática (2 vagas), Ensino de Ciências e Matemática, Micrometeorologia, Meteorologia e Imunologia Aplicada",
    vagas: "8 vagas",
    campi: "Santa Maria/RS",
    titulacao: "Doutorado. Classe Assistente",
    remuneracao: "Conforme titulação, em dedicação exclusiva",
    regime: "Dedicação exclusiva",
    banca: "PROGEP/UFSM",
    link_oficial: "https://www.ufsm.br/pro-reitorias/progep/editais/198-2026",
    inscricao: { inicio: "2026-06-30", fim: "2026-07-29", situacao: "encerrada", taxa: "R$ 412,60" },
    detalhamento: "completo",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-09-13", fim: "2026-12-27", nota: "Período provável das provas. Até 11/09 nenhum cronograma por área foi publicado, e o edital exige publicação com no mínimo 10 dias corridos de antecedência" },
        detalhe: { nota_minima: "7,00" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-09-13", fim: "2026-12-27", nota: "Dentro do período provável das provas. Até 11/09 nenhum cronograma por área foi publicado" },
        detalhe: { duracao: "Aula de no mínimo 40 e no máximo 50 minutos",
                   sorteio: "Sim. Ponto sorteado exatamente 24 horas antes do início da aula",
                   nota_minima: "7,00 na nota da 2ª etapa. O edital não fixa mínimo isolado para a didática",
                   arguicao: "Facultativa, de até 15 minutos após a aula",
                   modalidade: "Presencial, em sessão pública" } },
      { nome: "Prova Prática (quando cabível)", tipo: "outra", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Defesa de Produção Intelectual", tipo: "memorial", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "A inscrição já fechou e a prova didática ainda não tem data. O período provável começa em 13/09, mas até 11/09 nenhum cronograma por área tinha saído, e o edital exige pelo menos 10 dias de aviso. Se você está inscrito, o que manda é o sorteio 24 horas antes e a média 7,0 na segunda etapa."
  },

  // ══════════ UEMA · bloco de editais retomado em 04/09 ══════════
  {
    id: "uema-2026", logo: "uema.png",
    uf: "MA", sigla: "UEMA",
    instituicao: "Universidade Estadual do Maranhão",
    nivel: "Magistério Superior",
    numero_edital: "Editais nº 129, 130, 132, 133, 134, 137 e 139/2026-GR, retomados pelo Edital nº 241/2026",
    areas: "Medicina, Enfermagem, Psicologia, Direito, Agronomia, Matemática, Educação, Biologia, Letras e Educação Especial Inclusiva",
    vagas: "47 vagas imediatas mais cadastro de reserva no bloco original",
    campi: "São Luís, Caxias, Timon, Balsas, Santa Inês, Zé Doca, Grajaú, Coelho Neto, Colinas e outros, em 15 cidades",
    titulacao: "Doutorado na área. Cargo de Professor Adjunto",
    remuneracao: "R$ 11.294,38 (vencimento de R$ 7.058,99 mais gratificação de incentivo de 50%)",
    regime: "Estatutário estadual, 40 horas",
    banca: "Comissão própria, via concursoseseletivos.uema.br",
    link_oficial: "https://concursoseseletivos.uema.br",
    inscricao: { inicio: "2026-04-17", fim: "2026-05-25", situacao: "encerrada", taxa: "R$ 300,00" },
    detalhamento: "completo",
    etapas: [
      { nome: "Suspensão do certame por decisão judicial", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-07-23", nota: "Edital 234/2026 suspendeu o bloco 129 a 140" }, detalhe: {} },
      { nome: "Retomada da tramitação", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-09-04", nota: "Edital 241/2026 retomou os editais 129, 130, 132, 133, 134, 137 e 139" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "O calendário anterior previa início das provas em 28/08. Após a retomada, a nova data ainda não foi republicada" },
        detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "nao_divulgada", nota: "Nova data ainda não republicada após a retomada de 04/09. Acompanhe o site da UEMA diariamente" },
        detalhe: { duracao: "Aula de 45 a 55 minutos",
                   sorteio: "Sim. Tema sorteado da lista, excluído o da prova escrita, e comum a todos os candidatos",
                   nota_minima: "7,0",
                   arguicao: "Facultativa, de até 10 minutos por examinador, após a aula",
                   plano_de_aula: "Três vias, entregues no início da prova. A não entrega elimina na hora",
                   modalidade: "Prova pública, vedada a presença dos demais candidatos. Ordem pela inscrição" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Este é o mais imprevisível do radar. O concurso ficou parado por liminar de julho a setembro e acabou de voltar, em 04/09. Quem está inscrito precisa olhar o site da UEMA todo dia, porque o novo calendário sai a qualquer momento e o intervalo entre convocação e aula tende a ser curto. Regra dura de plano de aula: três vias na mão ou eliminação. Os editais 131, 135, 136, 138 e 140 seguem suspensos."
  },

  // ══════════ UFGD · Edital CCS 5/2026 (MS · didática 19 e 20/09) ══════════
  {
    id: "ufgd-5-2026",
    uf: "MS", sigla: "UFGD",
    instituicao: "Universidade Federal da Grande Dourados",
    nivel: "Magistério Superior",
    numero_edital: "Edital de Abertura CCS nº 5/2026 (CDPT 2026), com Retificações CCS nº 1 e 2/2026",
    areas: "Pedagogia e Educação em Espaços Escolares e Não Escolares (FAED), Metodologia do Ensino do Teatro (FALE), e Engenharia Elétrica, Gestão e Tecnologia da Produção e Processos Biotecnológicos (FAEN)",
    vagas: "5 vagas",
    campi: "Dourados/MS",
    titulacao: "Doutorado (Classe A)",
    remuneracao: "R$ 13.288,85 + auxílio-alimentação de R$ 1.175,00",
    regime: "40 horas com dedicação exclusiva",
    banca: "Centro de Seleção da UFGD",
    link_oficial: "https://portal.ufgd.edu.br/vestibular/docente-de-provas-e-titulos-cdpt/cdpt-2026",
    inscricao: { inicio: "2026-07-02", fim: "2026-07-22", situacao: "encerrada", taxa: "R$ 200,00" },
    detalhamento: "basico",
    etapas: [
      { nome: "Sorteio dos pontos das provas escrita e didática", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-08-29", nota: "Já realizado, em sessão virtual. O ponto da aula já é conhecido" }, detalhe: {} },
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-08-30", nota: "Já realizada. Resultado preliminar em 10/09, com recurso em 11/09" },
        detalhe: { duracao: "Até 3 horas, texto de 2 a 10 laudas", nota_minima: "7,00" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória · peso 4",
        data: { tipo: "periodo", valor: "2026-09-19", fim: "2026-09-20", nota: "Datas do cronograma divulgado na abertura. A convocação específica para a didática ainda não saiu" },
        detalhe: { duracao: "Aula de 40 a 50 minutos. Sair do intervalo custa 1 ponto",
                   sorteio: "Ponto sorteado em 29/08, junto com o da prova escrita",
                   nota_minima: "7,00",
                   arguicao: "Sim, 15 minutos, com até 5 minutos por resposta",
                   modalidade: "Presencial em Dourados/MS, com gravação",
                   plano_de_aula: "Obrigatório, com cópia física para a banca" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória · peso 3",
        data: { tipo: "nao_divulgada", nota: "Envio em PDF em ambiente virtual, data a divulgar" }, detalhe: {} },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Aqui o ponto da aula saiu em 29/08, três semanas antes da didática. Ninguém chega de surpresa, então a banca compara aulas preparadas com tempo. Peso 4 na didática, arguição de 15 minutos e plano de aula impresso obrigatório. Acompanhe a convocação no portal do CDPT 2026."
  },

  // ══════════ UFU · Edital 118/2026 (MS · escrita 27/09 · didáticas de 27/10 a 11/11) ══════════
  {
    id: "ufu-118-2026", logo: "ufu.png",
    uf: "MG", sigla: "UFU",
    instituicao: "Universidade Federal de Uberlândia",
    nivel: "Magistério Superior",
    numero_edital: "Edital PROGEP nº 118/2026 (condições gerais), com editais de condições específicas nº 119 a 126/2026",
    areas: "Engenharia de Computação e Inteligência Artificial, Engenharia Civil (Mecânica dos Solos), Agronomia (Fisiologia de Plantas e Melhoramento Vegetal), Probabilidade e Estatística, Saúde Coletiva, Ciência da Computação e Engenharia Elétrica (Telecomunicações)",
    vagas: "10 vagas",
    campi: "Uberlândia (Santa Mônica, Glória e Umuarama), Ituiutaba (Pontal) e Patos de Minas",
    titulacao: "Doutorado na área, com graduação conforme a vaga",
    remuneracao: "R$ 13.753,95 (40h DE com doutorado) + auxílio-alimentação de R$ 1.192,00",
    regime: "40 horas com dedicação exclusiva",
    banca: "PROGEP/DIRPS UFU, com comissões por unidade",
    link_oficial: "https://www.portalselecao.ufu.br/servicos/Edital/listar/docente",
    inscricao: { inicio: "2026-08-04", fim: "2026-08-19", situacao: "encerrada", taxa: "R$ 320,00" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória e classificatória",
        data: { tipo: "exata", valor: "2026-09-27", nota: "Das 10h às 14h" },
        detalhe: { duracao: "Até 4 horas", nota_minima: "70 pontos", modalidade: "Presencial" } },
      { nome: "Prova de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "periodo", valor: "2026-10-26", fim: "2026-11-10", nota: "Envio por e-mail à unidade, na data do cronograma de cada edital específico" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "Eliminatória e classificatória",
        data: { tipo: "periodo", valor: "2026-10-27", fim: "2026-11-11", nota: "Cada edital específico tem data própria. FEELT 121 e 122 e ICENP 123 em 27/10; ICIAG 124 em 28/10; FACOM 120 e ICIAG 126 em 04/11; IME 119 em 10/11; ICIAG 125 em 11/11" },
        detalhe: { duracao: "Aula de 40 a 50 minutos",
                   sorteio: "Sim. Ordem e tema sorteados em sessão pública, entre 24 e 36 horas antes da aula",
                   nota_minima: "70 pontos",
                   arguicao: "Sim, até 30 minutos",
                   modalidade: "Presencial. Remota nos editais 121 (Teams) e 123 (ConferênciaWeb)",
                   plano_de_aula: "Entregue no dia da prova, antes do início" } },
      { nome: "Defesa de Projeto (somente FACOM, Edital 120)", tipo: "outra", carater: "",
        data: { tipo: "exata", valor: "2026-11-05", nota: "Às 9h, com sorteio da ordem às 8h30" }, detalhe: {} },
      { nome: "Resultado final", tipo: "resultado", carater: "",
        data: { tipo: "nao_divulgada", nota: "Não consta nos cronogramas publicados" }, detalhe: {} }
    ],
    observacao: "O tema sai na véspera e a aula tem de 40 a 50 minutos, com até 30 minutos de arguição e nota mínima 70. Entre a escrita de 27/09 e a aula há um mês ou mais, conforme o seu edital específico: é tempo para ensaiar com cronômetro todos os pontos da lista."
  },

  // ══════════ UFMG · Editais 1.632 e 1.633/2026 (MS · Escola de Belas Artes · provas até meados de novembro) ══════════
  {
    id: "ufmg-1632-1633-2026",
    uf: "MG", sigla: "UFMG",
    instituicao: "Universidade Federal de Minas Gerais, Escola de Belas Artes",
    nivel: "Magistério Superior",
    numero_edital: "Editais nº 1.632 e nº 1.633, de 13/07/2026 (DOU de 16/07/2026)",
    areas: "Departamento de Desenho: Desenho e Artes Visuais (Edital 1.632) e Experimentação e Produção em Moda e Design de Moda (Edital 1.633)",
    vagas: "2 vagas, uma por edital",
    campi: "Belo Horizonte/MG, Escola de Belas Artes",
    titulacao: "Doutorado em Artes ou áreas afins no Edital 1.632. Mestrado em Moda, Design, Artes, Arquitetura, Comunicação, Humanidades ou áreas correlatas no Edital 1.633. Classe Assistente A, nível 1",
    remuneracao: "R$ 13.288,85 com doutorado. R$ 9.271,29 com mestrado no Edital 1.633",
    regime: "40 horas com dedicação exclusiva",
    banca: "Comissões examinadoras da Escola de Belas Artes",
    link_oficial: "https://www.eba.ufmg.br/index.php/concurso-publico-para-professor-assistente-classe-a-nivel-1-departamento-de-desenho-area-de-conhecimento-desenho-e-artes-visuais/2026/07/",
    inscricao: { inicio: "2026-07-17", fim: "2026-08-17", situacao: "encerrada", taxa: "R$ 215,99" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita (somente Edital 1.633)", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "nao_divulgada", nota: "As provas começam entre 30 e 90 dias após 17/08, com convocação publicada com no mínimo 15 dias de antecedência" },
        detalhe: { duracao: "Até 5 horas", nota_minima: "70%" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Na janela de 30 a 90 dias após 17/08. Nenhuma convocação publicada até 11/09" },
        detalhe: { duracao: "Exposição de 50 minutos",
                   sorteio: "Sim. Ponto sorteado com no mínimo 24 horas de antecedência",
                   nota_minima: "Média de 70 pontos no Edital 1.632. Confira o Edital 1.633",
                   arguicao: "Sim, oral, pela comissão",
                   modalidade: "Presencial, em sessão pública" } },
      { nome: "Prova Prática de desenho de observação (Edital 1.632)", tipo: "outra", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Na mesma janela" }, detalhe: { duracao: "Até 4 horas" } },
      { nome: "Análise de portfólio (Edital 1.633)", tipo: "outra", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Após a prova escrita" }, detalhe: { formato: "20 a 30 imagens" } },
      { nome: "Julgamento de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada" }, detalhe: {} }
    ],
    observacao: "Pela regra do edital, as provas começam até meados de novembro, e a convocação sai com só 15 dias de aviso. No Edital 1.632 não há prova escrita, então a aula de 50 minutos e a prova prática decidem o resultado. O Edital 1.633 tem página própria no site da Escola de Belas Artes."
  },

  // ══════════ UFMG · Edital 1.638/2026 (MS · Instituto de Geociências · inscrição até 11/09) ══════════
  {
    id: "ufmg-1638-2026",
    uf: "MG", sigla: "UFMG",
    instituicao: "Universidade Federal de Minas Gerais, Instituto de Geociências",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 1.638, de 13/07/2026 (DOU de 16/07/2026), retificado pelo Edital nº 1.706/2026",
    areas: "Geociências: Cartografia e Geodésia, no Departamento de Cartografia",
    vagas: "1 vaga, ampla concorrência",
    campi: "Belo Horizonte/MG, Instituto de Geociências",
    titulacao: "Doutorado na área do concurso ou em áreas afins. Classe Assistente A, nível 1",
    remuneracao: "R$ 13.753,96 (vencimento R$ 6.397,19 + RT de doutorado R$ 7.356,77)",
    regime: "40 horas com dedicação exclusiva",
    banca: "Comissão examinadora designada pela direção do Instituto de Geociências",
    link_oficial: "https://igc.ufmg.br/editais/editais-de-concursos-abertos/",
    inscricao: { inicio: "2026-07-29", fim: "2026-09-11", situacao: "aberta", taxa: "R$ 215,99" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Escrita", tipo: "discursiva", carater: "Eliminatória",
        data: { tipo: "nao_divulgada", nota: "As provas começam entre 30 e 90 dias após o fim das inscrições, com convocação publicada com no mínimo 15 dias de antecedência" },
        detalhe: { duracao: "Até 5 horas, com a primeira hora para consulta bibliográfica", nota_minima: "70%" } },
      { nome: "Prova Didática", tipo: "didatica", carater: "Segunda fase",
        data: { tipo: "nao_divulgada", nota: "Após a prova escrita, na mesma janela de 30 a 90 dias. Aguarde o edital de convocação" },
        detalhe: { duracao: "Exposição de 50 minutos",
                   sorteio: "Sim. Ponto da lista da comissão sorteado com no mínimo 24 horas de antecedência",
                   arguicao: "Sim, oral, pela comissão",
                   modalidade: "Presencial" } },
      { nome: "Julgamento de Títulos", tipo: "titulos", carater: "Classificatória",
        data: { tipo: "nao_divulgada", nota: "Após a prova escrita" }, detalhe: {} }
    ],
    observacao: "Último dia de inscrição em 11/09. A convocação para as provas sai com apenas 15 dias de aviso, então a lista de pontos precisa estar estudada antes dela. A escrita tem uma hora inicial de consulta bibliográfica: leve o material organizado."
  },

  // >>>>>>>>>> INÍCIO DO BLOCO UNCISAL: SUBSTITUA ATÉ A MARCA DE FIM PELO BLOCO UNCISAL DO SEU dados.js LOCAL <<<<<<<<<<
  // ══════════ UNCISAL · Edital 01/2026 (MS estadual · objetiva 22/11) ══════════
  {
    id: "uncisal-01-2026", logo: "uncisal.png",
    uf: "AL", sigla: "UNCISAL",
    instituicao: "Universidade Estadual de Ciências da Saúde de Alagoas",
    nivel: "Magistério Superior",
    numero_edital: "Edital nº 01/2026",
    areas: "Consulte o edital",
    vagas: "Consulte o edital",
    campi: "Consulte o edital",
    titulacao: "Consulte o edital",
    remuneracao: "Consulte o edital",
    regime: "Consulte o edital",
    banca: "Cebraspe",
    link_oficial: "https://www.cebraspe.org.br/concursos/uncisal_26",
    inscricao: { inicio: null, fim: null, situacao: "consultar" },
    detalhamento: "basico",
    etapas: [
      { nome: "Prova Objetiva", tipo: "objetiva", carater: "",
        data: { tipo: "nao_divulgada", nota: "Consulte o cronograma no portal do Cebraspe" }, detalhe: {} },
      { nome: "Prova Didática", tipo: "didatica", carater: "",
        data: { tipo: "nao_divulgada", nota: "Consulte o cronograma no portal do Cebraspe" }, detalhe: {} }
    ],
    observacao: "Confira edital, retificações e cronograma no portal do Cebraspe."
  }
  // >>>>>>>>>> FIM DO BLOCO UNCISAL <<<<<<<<<<

];
